"""change 'condition' to 'cost'

Revision ID: 23668f3af9dc
Revises: fe33451d7b10
Create Date: 2023-11-30 20:27:46.426772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23668f3af9dc'
down_revision = 'fe33451d7b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Integer(), nullable=True))
        batch_op.drop_column('condition')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', sa.INTEGER(), nullable=True))
        batch_op.drop_column('cost')

    # ### end Alembic commands ###
