"""remove is_new from Product

Revision ID: fe33451d7b10
Revises: 7074862ed2c4
Create Date: 2023-11-30 20:21:37.591011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe33451d7b10'
down_revision = '7074862ed2c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('is_new')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_new', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
